### ISSUE TITLE
Online preview

### ISSUE THREAD

**Issue by rm-code** [love2d-community/splashes#10]
Would be cool to have an online preview via love.js and gh-pages!

**Comment by s-ol** [comment]
I'm gonna see if I can have travis auto-compile and push to pages; should work!

**Comment by rm-code** [comment]
I might _borrow_ your travis file if you get that to work :smiling_imp:

**Comment by s-ol** [comment]
@rm-code fails on my laptop, but could be my GPU. Could you test https://love2d-community.github.io/splashes for me?

I think the travis script should work now

**Comment by rm-code** [comment]
Hm it fails for me too. According to the js console it doesn't find some of the resources ...

![screenshot 2016-02-20 17 06 58](https://cloud.githubusercontent.com/assets/11627131/13197650/799bcd32-d7f4-11e5-9c34-f0b1cfca1e9a.png)

**Comment by s-ol** [comment]
Those two are not the issue; I tried with the debug `love.js` and it was an issue compiling the shader.

**Comment by s-ol** [comment]
nope, not working just yet. Gonna check back later

**Comment by rm-code** [comment]
Just wanted to say that it is still failing :D

**Comment by s-ol** [comment]
@rm-code could you maybe test compiling this repo with the regular emscripten compiler and see if it works that way? Maybe my ruby packager is screwing something up (though I would expect very different errors)

**Comment by s-ol** [comment]
@rm-code the page doesn't need to work, as long as travis commits and pushes to `gh-pages` this issue is close-able. It pushes but it somehow doesn't commit (yet).

**Comment by rm-code** [comment]
Sure, I'm back home in a few hours :+1:

**Comment by s-ol** [comment]
Damn it, accidentally closed in commit msg

**Comment by s-ol** [comment]
wow.... I feel a bit stupid. It was working the whole time, it just didnt have anything to commit because I didn't change the example -.-'

@rm-code if you want to copy the setup, make sure to generate your own public/private key pair, encrypt it with the `travis` gem and update the decryption part of `.travis.yml` (see the travis manual for all this).

**Comment by rm-code** [comment]
@S0lll0s Does the online example run for you? I still get a .js error :frowning:

**Comment by s-ol** [comment]
Thats why I asked you whether you could try compiling the example by hand, emscripten/lovejs doesn't run at all on the laptop I'm travelling with rn.
The Travis build is working though, still. I think this is a lovejs issue but like I said I can't debug lovejs with my hardware atm.
On Feb 21, 2016 11:20 AM, Robert Machmer notifications@github.com wrote:@S0lll0s Does the online example run for you? I still get a .js error

**Comment by rm-code** [comment]
Ah, I misunderstood. I thought the love.js build was working the whole time ... I'll try compiling it now.

**Comment by rm-code** [comment]
Ok it fails for me too when I build it myself. Maybe a problem with the shaders?

![screenshot 2016-02-21 12 06 40](https://cloud.githubusercontent.com/assets/11627131/13202241/d11eee28-d893-11e5-8ee9-26208637eefe.png)

**Comment by s-ol** [comment]
Yes, that's what I thought - paging @TannerRogalsky - this is a love.js issue as far as I can tell (or maybe another bug in vrld/z0rgs shaders, they had a few undefined behaviours in their original ones that broke on certain gpus/drivers)

**Comment by TannerRogalsky** [comment]
@S0lll0s It's really impossible to debug exceptions with the release build. Use the debug build if there are errors: https://github.com/TannerRogalsky/love.js/tree/master/debug

**Comment by TannerRogalsky** [comment]
```
(index):1257 Line 29: ERROR: '-' :  wrong operand types  no operation '-' exists that takes a left-hand operand of type 'const int' and a right operand of type 'mediump float' (or there is no acceptable conversion)Module.printErr @ (index):1257
(index):1257 Line 29: ERROR: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type 'const 4-component vector of float' and a right operand of type 'const int' (or there is no acceptable conversion))
```

Welcome to OpenGL ES2. There's no implicit conversion between ints and floats. You have to stick a `.0` at the end of ints.

**Comment by TannerRogalsky** [comment]
Also, I'll save you some time: `smoothstep` doesn't exist in ES2.

**Comment by s-ol** [comment]
@TannerRogalsky I tried, but like I said earlier I emscripten and love.js won't run properly in the first place on my laptop, so it doesn't matter.
On Feb 21, 2016 3:14 PM, Tanner Rogalsky notifications@github.com wrote:@S0lll0s It's really impossible to debug exceptions with the release build. Use the debug build if there are errors: https://github.com/TannerRogalsky/love.js/tree/master/debug
