### ISSUE TITLE
Fix Shader for OpenGL ES 2.0 feature set

### ISSUE THREAD

**Issue by s-ol** [love2d-community/splashes#11]
- fix use of int/float types
- don't rely in `smoothstep`

This is what currently causes the issues with the gh-pages /love.js builds.

**Comment by rm-code** [comment]
I'll see what I can do. Wanted to get back into GLSL coding anyway.

**Comment by rm-code** [comment]
Welp ... @TannerRogalsky was faster :D

**Comment by JanWerder** [comment]
:laughing:

**Comment by JanWerder** [comment]
I still seems to crash

**Comment by rm-code** [comment]
Yup, same here.

**Comment by TannerRogalsky** [comment]
@JanWerder @rm-code Please read through that PR. There is another issue.

**Comment by TannerRogalsky** [comment]
I'm going to provide a 'compatibility' build going forward to avoid issues like this. Performance and file size take a hit but it should be easier to work with. https://github.com/TannerRogalsky/love.js/tree/master/release-compatibility

**Comment by s-ol** [comment]
Can someone verify that `love2d-community.github.io/splashes` does now work with the compat love.js?

**Comment by rm-code** [comment]
On it.

**Comment by TannerRogalsky** [comment]
@S0lll0s I'm getting the following error:

```
Error: [string "boot.lua"]:432: No code to run
love.js:1 Your game might be packaged incorrectly
love.js:1 Make sure main.lua is at the top level of the zip
love.js:1 stack traceback:
love.js:1   (tail call): ?
love.js:1   [C]: in function 'error'
love.js:1   [string "boot.lua"]:432: in function <[string "boot.lua"]:274>
love.js:1   [C]: in function 'xpcall'
```

**Comment by s-ol** [comment]
hm, for some reason love.js completely wrecks my browser. Can't even debug this situation right now until I get back home in 2-3 weeks :/

**Comment by slime73** [comment]
> don't rely in `smoothstep`

smoothstep works fine in OpenGL ES 2's shading language.

**Comment by TannerRogalsky** [comment]
@slime73 https://github.com/love2d-community/splashes/pull/12#issuecomment-186835296 :D :D

**Comment by s-ol** [comment]
So  think this is done then?
