### ISSUE TITLE
Portability Issues

### ISSUE THREAD

**Issue by videah** [love2d-community/splashes#15]
Because lg.newImage takes slashes instead of dots, the current_folder variable causes problems if the splash folder is not at root level.

**Comment by josefnpat** [comment]
This is the page that I got the current_folder from: http://kiki.to/blog/2014/04/12/rule-5-beware-of-multiple-files/

**Comment by s-ol** [comment]
@josefnpat he means for the assets, not `require`. We just need to do `current_folder:gsub("%.", "/") .. "/heart.png"` etc.
