### ISSUE TITLE
Don't monkey-patch LÖVE APIs

### ISSUE THREAD

**Issue by slime73** [love2d-community/splashes#16]
[This](https://github.com/love2d-community/splashes/blob/master/o-ten-one/init.lua#L147) will globally change `Shader:send` in anyone's LÖVE game which loads the file. Please don't do that!

Just use `Shader:getExternVariable` before calling `Shader:send`, in the code which actually calls it, if you really need to.

**Comment by josefnpat** [comment]
:+1:
