### ISSUE TITLE
Remove the ®

### ISSUE THREAD

**Issue by Sheepolution** [love2d-community/splashes#18]
> Later, when I designed the logo (the curvy LÖVE text), I added the umlauts on a whim since I decided that something was missing from the logo. That's how it became LÖVE. I also added a sarcastic copyright symbol to the logo, although **that is removed now**.

[Source](http://blogs.love2d.org/content/l%C3%B6vely-interviews-rude)

You can also see on the [homepage](https://www.love2d.org/) that there is no ® in the logo. Only on the [wiki](https://www.love2d.org/wiki/Main_Page), but probably because no one bothered to change it.

**Comment by JanWerder** [comment]
Good catch!
Ok, so pretty much only the log.png & logo_mask.png need to be changed
