### ISSUE TITLE
Chiptune music

### ISSUE THREAD

**Issue by davisdude** [love2d-community/splashes#7]
There's a "what is love" chiptune out there that many people used for their splash screens before. I know @josefnpat has contacted the artist before. Would it be possible to get a general license to use the song to be include with the library? What contingencies would there be?

**Comment by s-ol** [comment]
It's available as an easter-egg on the love2d homepage ([direct link](https://love2d.org/love.ogg)), I think someone once linked a youtube upload that had the artists name....

**Comment by josefnpat** [comment]
So the music was made by Daniel Bienvenu.

I contacted him about some form of license for the music, and this was the response I got:

> Hello,
> 
> Thanks for forwarding the mail.
> 
> Well, that's always nice to see there are still people respecting the work of others and ask first if it's possible to use or not.
> 
> By this email I'm allowing you to use the music "cv - what is love" under the simple condition to be credited for it, regardless if you gain money or not for your games, and let me know if it's possible to get a copy of the game(s) using this music when done so I can too appreciate your work.
> 
> Best regards,
> 
> Daniel Bienvenu

I use it in the lovesplash repo, which you will note, comes with no specific FOSS license: https://github.com/josefnpat/lovesplash

Unfortunately, due to the wording, he is only allowing myself to use the music, although further inquiry may provide a better license of some sort. (Perhaps something upon behalf of the love community?)

The email I contacted him at was: daniel.bienvenu at hotmail.com

If you like, I can contact him again asking him for permission to use this with open source projects within the love community.

**Comment by s-ol** [comment]
It would be awesome if we could get a license that allows everyone to use the song in a way that connects it to LÖVE and as long as he is credited for it in source and binary distributions.

**Comment by josefnpat** [comment]
I will hit him up then!

**Comment by JanWerder** [comment]
:+1:
Am 17.02.2016 17:42 schrieb "Seppi" notifications@github.com:

**Comment by josefnpat** [comment]
> "What is Love" usage for OSS projects
> 1 message
> Josef Patoprsty josefnpat@gmail.com  Wed, Feb 17, 2016 at 10:54 AM
> To: daniel.bienvenu@hotmail.com
> Dear Daniel,
> 
> A few years ago (2012, wow it's been a long time!) I asked for permission to use your "cv - what is love" music in my games, and I have actually used it in a splash screen library I made, which has been in almost every game I have made since then!
> 
> I posted the credit in the library that I wrote along with it: https://github.com/josefnpat/lovesplash
> 
> It has come to my attention that members of the LÖVE community (http://love2d.org and specifically from https://github.com/love2d-community) would very much like to use this music as well in open source projects. The problem is that when I requested usage for the music in 2012, the wording defined it was only for me, and not the love community.
> 
> I was wondering if you would be willing to offer the "cv - what is love" music under a more liberal license. May I suggest the Creative Commons Attribution 2.0 Generic license?
> 
> As originally requested in your response in 2012 and a token goodwill (regardless of how you decide to respond to my inquiry), if you see any paid games on my website that interest you, please tell me which ones so I can send you free download keys!
> 
> My website is here and all my paid games are here.
> 
> On behalf of the LÖVE community and myself, thank you very much for your time.
> 
> -Josef Patoprsty (@josefnpat)
> 
> P.S. - If you would like to join our public discussion, you can find it here on github!

**Comment by zorggn** [comment]
This would also be optional, right? I mean, the song itself is quite long, and the splash is over fairly quickly, seems logical that it should be... or is this only meant for the demo main.lua?

**Comment by davisdude** [comment]
Well, typically the song fades out.
Of course you could also do whatever song you like, it just seems convenient for most purposes.

**Comment by josefnpat** [comment]
@zorggn I have a cut version here: https://github.com/josefnpat/lovesplash/blob/master/lovesplash/love_short.ogg

**Comment by s-ol** [comment]
@zorggn I would use the cut version (maybe adjust again if the length doesn't fit) and add an option so you can override the audio with your own `Source` object or disable it completely.

**Comment by zorggn** [comment]
Okay. :smirk_cat:

**Comment by s-ol** [comment]
Added everything but the actual audio file - `love_short.ogg` is way longer than the splash currently is (it's 2.44s without the optional delays before and after).

We could make default delays that match the audio length that get implied when leaving audio.

Either way, I don't really have audio editing tools around so it would be nice if someone would cut us a nice snippet that we can push once we (hopefully!) get the license to do so.

**Comment by zorggn** [comment]
At work at the moment, but if no one else decides to do it for 14 hours, i'll do it.

**Comment by josefnpat** [comment]
Nice.  Need to make sure not to add the audio until we get permission.

**Comment by zorggn** [comment]
[here](https://dl.dropboxusercontent.com/u/36445632/love-short-edit.ogg)'s what i came up with, containing the most recognizable parts, about pi seconds long (accidental, i swear :3) With or without a tiny delay in the beginning, it could work, but it's not my call.

**Comment by josefnpat** [comment]
@zorggn that's nice! Can you also do a Haddaway cover?

I don't think there's any problem using the melody for Haddaway's "What Is Love". It's very recognizable, and entirely tongue and cheek.

**Comment by zorggn** [comment]
@josefnpat i just did: https://dl.dropboxusercontent.com/u/36445632/music/160219_lovesplashident.ogg May be a bit "busy" though, probably could thin the sound a bit, or idk.

**Comment by s-ol** [comment]
hm, i forgot what the status of this was. anyone remember what was left to do?

**Comment by JanWerder** [comment]
I think there wasn't a good enough sample for the intro
